'use strict';

function createServerDebugger(panel,options) {
  const stateLabel=panel.querySelector('#debug-state'),targetSelect=panel.querySelector('#debug-target'),routine=panel.querySelector('#debug-routine'),argumentsInput=panel.querySelector('#debug-arguments'),stack=panel.querySelector('#debug-stack'),variables=panel.querySelector('#debug-variables'),watchesHost=panel.querySelector('#debug-watches'),watchInput=panel.querySelector('#debug-watch-input');
  let snapshot=null,selectedFrame=0,pollTimer=0,heartbeatTimer=0,watches=[];
  const mutationHeaders={'Content-Type':'application/json','X-ML-CSRF':'1'};
  const terminal=state=>['completed','failed','stopped'].includes(state);
  function open(){panel.hidden=false;document.body.classList.add('debug-open');const suggested=options.routineAtCursor();if(suggested)routine.value=suggested;safe(refreshTargets)}
  function close(){panel.hidden=true;document.body.classList.remove('debug-open')}
  async function request(path,method='GET',body){const init={method,headers:method==='GET'?{}:mutationHeaders};if(body!==undefined)init.body=JSON.stringify(body);const response=await fetch(path,init);if(!response.ok)throw new Error((await response.text()).trim());return response.json()}
  async function refreshTargets(){const selected=targetSelect.value,targets=await request('/api/debug/targets');targetSelect.replaceChildren(option('','Локальный сервер Studio'));for(const target of targets){const label=`${kindText(target.kind)} · ${target.name}${target.attached?` · занят: ${target.attachedBy}`:''}`,item=option(target.id,label);item.disabled=target.attached;targetSelect.append(item)}if(Array.from(targetSelect.options).some(item=>item.value===selected&&!item.disabled))targetSelect.value=selected}
  function option(value,label){const item=document.createElement('option');item.value=value;item.textContent=label;return item}
  function kindText(kind){return kind==='client'?'Клиент':kind==='userSession'?'Сеанс':kind==='scheduledJob'?'Регламентное задание':'Фоновое задание'}
  async function start(){const file=options.current();if(!file||file.isForm||file.language!=='bsl')throw new Error('Откройте BSL-модуль.');const name=routine.value.trim()||options.routineAtCursor();if(!name)throw new Error('Укажите процедуру или функцию для запуска.');let args=[];try{args=JSON.parse(argumentsInput.value||'[]')}catch{throw new Error('Параметры должны быть корректным JSON-массивом.')}if(!Array.isArray(args))throw new Error('Параметры должны быть JSON-массивом.');routine.value=name;snapshot=await request('/api/debug/start','POST',{targetId:targetSelect.value,path:file.path,content:options.source(),routine:name,arguments:args,breakpoints:options.breakpoints()});selectedFrame=0;await render();pollIfRunning()}
  async function command(action){if(!snapshot)return;snapshot=await request('/api/debug/command','POST',{action});await render();pollIfRunning()}
  async function pause(){if(!snapshot)return;snapshot=await request('/api/debug/pause','POST');await render();pollIfRunning()}
  async function stop(){if(!snapshot)return;snapshot=await request('/api/debug/session','DELETE');await render()}
  async function poll(){clearTimeout(pollTimer);if(!snapshot||terminal(snapshot.state))return;try{snapshot=await request('/api/debug/state');await render()}catch(error){stateLabel.textContent=error.message;stateLabel.className='error';return}pollIfRunning()}
  function pollIfRunning(){clearTimeout(pollTimer);if(snapshot?.state==='running')pollTimer=setTimeout(poll,140)}
  function updateHeartbeat(){const active=snapshot&&!terminal(snapshot.state);if(active&&!heartbeatTimer)heartbeatTimer=setInterval(()=>request('/api/debug/heartbeat','POST').catch(error=>{stateLabel.textContent=error.message;stateLabel.className='error'}),5000);else if(!active&&heartbeatTimer){clearInterval(heartbeatTimer);heartbeatTimer=0}}
  async function syncBreakpoints(){if(!snapshot||terminal(snapshot.state))return;try{snapshot=await request('/api/debug/breakpoints','PUT',{breakpoints:options.breakpoints()});await render()}catch(error){stateLabel.textContent=error.message;stateLabel.className='error'}}
  function stateText(){if(!snapshot)return'Отладчик не запущен';if(snapshot.state==='paused')return`Остановлено: ${snapshot.reason}${snapshot.message?' · '+snapshot.message:''}`;if(snapshot.state==='completed')return`Завершено · ${snapshot.result?.value||'Undefined'}`;if(snapshot.state==='failed')return`Ошибка · ${snapshot.error||''}`;if(snapshot.state==='stopped')return'Остановлено пользователем';return'Выполняется…'}
  async function selectFrame(index,navigate=true){selectedFrame=Math.max(0,Math.min(index,(snapshot?.frames?.length||1)-1));renderFrames();renderVariables();await evaluateWatches();if(navigate&&snapshot?.frames?.[selectedFrame])await options.showLocation(snapshot.frames[selectedFrame])}
  function renderFrames(){stack.replaceChildren();for(const frame of snapshot?.frames||[]){const button=document.createElement('button'),name=document.createElement('span'),place=document.createElement('small');button.type='button';button.className=`debug-frame${frame.id===selectedFrame?' selected':''}`;name.textContent=`${frame.module?frame.module+'.':''}${frame.routine}`;place.textContent=`${frame.location.path}:${frame.location.line}`;button.append(name,place);button.addEventListener('click',()=>selectFrame(frame.id));stack.append(button)}if(!stack.children.length)stack.append(empty('Стек появится при остановке'))}
  function renderVariables(){variables.replaceChildren();const frame=snapshot?.frames?.[selectedFrame];for(const item of frame?.variables||[]){const row=document.createElement('div'),name=document.createElement('span'),scope=document.createElement('span'),value=document.createElement('span');row.className='debug-variable';name.textContent=item.name;scope.className='debug-kind';scope.textContent=item.scope==='module'?'модуль':item.value.kind;value.className='debug-value';value.textContent=item.value.value;value.title=item.value.value;row.append(name,scope,value);variables.append(row)}if(!variables.children.length)variables.append(empty('Нет доступных переменных'))}
  async function evaluate(expression){return request('/api/debug/evaluate','POST',{frame:selectedFrame,expression})}
  async function evaluateWatches(){watchesHost.replaceChildren();for(const expression of watches){const row=document.createElement('div'),name=document.createElement('span'),kind=document.createElement('span'),value=document.createElement('span'),remove=document.createElement('button');row.className='debug-watch';name.textContent=expression;kind.className='debug-kind';value.className='debug-value';remove.textContent='×';remove.title='Удалить';remove.addEventListener('click',()=>{watches=watches.filter(item=>item!==expression);evaluateWatches()});try{if(snapshot?.state!=='paused')throw new Error('—');const result=await evaluate(expression);kind.textContent=result.kind;value.textContent=result.value;value.title=result.value}catch(error){row.classList.add('error');value.textContent=error.message==='—'?'—':error.message}row.append(name,kind,value,remove);watchesHost.append(row)}if(!watchesHost.children.length)watchesHost.append(empty('Добавьте вычисляемое выражение'))}
  async function addWatch(){const expression=watchInput.value.trim();if(!expression||watches.includes(expression))return;watches.push(expression);watchInput.value='';await evaluateWatches()}
  async function render(){if(snapshot?.state==='paused')selectedFrame=0;stateLabel.className=snapshot?.state==='failed'?'error':snapshot?.state==='paused'?'warning':'';stateLabel.textContent=stateText();panel.querySelectorAll('[data-debug-command]').forEach(button=>button.disabled=snapshot?.state!=='paused');panel.querySelector('#debug-pause').disabled=snapshot?.state!=='running';panel.querySelector('#debug-stop').disabled=!snapshot||terminal(snapshot.state);updateHeartbeat();renderFrames();renderVariables();await evaluateWatches();if(snapshot?.state==='paused'&&snapshot.frames?.[0])await options.showLocation(snapshot.frames[0]);else options.clearLocation()}
  function empty(text){const node=document.createElement('div');node.className='debug-empty';node.textContent=text;return node}
  async function safe(action){try{await action()}catch(error){stateLabel.textContent=String(error.message||error);stateLabel.className='error'}}
  panel.querySelector('#debug-start').addEventListener('click',()=>safe(start));panel.querySelector('#debug-pause').addEventListener('click',()=>safe(pause));panel.querySelector('#debug-stop').addEventListener('click',()=>safe(stop));panel.querySelector('#debug-close').addEventListener('click',close);panel.querySelectorAll('[data-debug-command]').forEach(button=>button.addEventListener('click',()=>safe(()=>command(button.dataset.debugCommand))));panel.querySelector('#debug-watch-add').addEventListener('click',()=>safe(addWatch));watchInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();safe(addWatch)}});
  window.addEventListener('pagehide',()=>{if(snapshot&&!terminal(snapshot.state))fetch('/api/debug/session',{method:'DELETE',headers:mutationHeaders,keepalive:true}).catch(()=>{})});
  return{open,syncBreakpoints};
}
