'use strict';

function createTestRunner(dialog,options) {
  const list=dialog.querySelector('#tests-list'),results=dialog.querySelector('#tests-results'),state=dialog.querySelector('#tests-state'),runAll=dialog.querySelector('#tests-run-all');
  const headers={'Content-Type':'application/json','X-ML-CSRF':'1'};
  let cases=[],running=false;
  async function request(path,method='GET',body){const response=await fetch(path,{method,headers:method==='GET'?{}:headers,body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)throw new Error((await response.text()).trim());return response.json()}
  async function open(){if(!dialog.open)dialog.showModal();await safe(refresh)}
  async function refresh(){state.textContent='Чтение тестов…';cases=await request('/api/tests');renderCases();state.textContent=`Тестов: ${cases.length}`}
  function renderCases(){list.replaceChildren();const modules=new Map();for(const item of cases){if(!modules.has(item.path))modules.set(item.path,[]);modules.get(item.path).push(item)}for(const [path,items] of modules){const module=document.createElement('section'),header=document.createElement('div'),title=document.createElement('span'),button=document.createElement('button');module.className='test-module';header.className='test-module-header';title.textContent=path;button.textContent='Запустить модуль';button.disabled=running;button.addEventListener('click',()=>safe(()=>run({path})));header.append(title,button);module.append(header);for(const item of items){const row=document.createElement('div'),name=document.createElement('a'),runButton=document.createElement('button');row.className='test-case';name.textContent=item.routine;name.title=`${item.path}:${item.line}`;name.addEventListener('click',()=>options.showLocation(item.path,item.line,1));runButton.textContent='▶';runButton.title='Запустить тест';runButton.disabled=running;runButton.addEventListener('click',()=>safe(()=>run({path:item.path,routine:item.routine})));row.append(name,runButton);module.append(row)}list.append(module)}if(!list.children.length)list.append(empty('Экспортные тестовые процедуры не найдены.'))}
  async function run(selection){if(running)return;if(!options.canRun())throw new Error('Сначала сохраните текущий файл.');running=true;runAll.disabled=true;renderCases();state.textContent='Выполнение…';state.className='muted';try{const report=await request('/api/tests/run','POST',selection);renderResults(report);state.textContent=`Пройдено: ${report.passed} · Ошибок: ${report.failed} · ${duration(report.duration)}`;state.className=report.failed?'error':''}finally{running=false;runAll.disabled=false;renderCases()}}
  function renderResults(report){results.replaceChildren();for(const item of report.results||[]){const card=document.createElement('article'),heading=document.createElement('div'),status=document.createElement('span'),name=document.createElement('strong'),elapsed=document.createElement('small');card.className=`test-result ${item.status}`;heading.className='test-result-title';status.textContent=item.status==='passed'?'✓':'✕';name.textContent=item.case.routine;elapsed.textContent=duration(item.duration);heading.append(status,name,elapsed);card.append(heading);if(item.error){const error=document.createElement('pre');error.className='test-error';error.textContent=item.error;card.append(error)}if(item.stack?.length){const stack=document.createElement('div');stack.className='test-stack';for(const frame of item.stack){const button=document.createElement('button');button.textContent=`${frame.module?frame.module+'.':''}${frame.routine} · ${frame.path}:${frame.line}`;button.addEventListener('click',()=>options.showLocation(frame.path,frame.line,frame.column));stack.append(button)}card.append(stack)}results.append(card)}if(!results.children.length)results.append(empty('Нет результатов.'))}
  function duration(nanoseconds){const milliseconds=Number(nanoseconds||0)/1e6;return milliseconds<1?'<1 мс':`${milliseconds.toFixed(milliseconds<100?1:0)} мс`}
  function empty(text){const node=document.createElement('div');node.className='tests-empty';node.textContent=text;return node}
  async function safe(action){try{await action()}catch(error){state.textContent=String(error.message||error);state.className='error'}}
  runAll.addEventListener('click',()=>safe(()=>run({})));dialog.querySelector('#tests-refresh').addEventListener('click',()=>safe(refresh));dialog.querySelector('#tests-close').addEventListener('click',()=>dialog.close());
  return{open};
}
