package metadata

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/k33alexey/MetaLab/internal/project"
	"github.com/k33alexey/MetaLab/internal/uuid"
)

const RoleKind Kind = "roles"

// Limits apply to decoded JSON as well as bounded YAML sources.
const MaxRolePermissions = 10_000

type PermissionOperation string

const (
	PermissionRead        PermissionOperation = "read"
	PermissionCreate      PermissionOperation = "create"
	PermissionUpdate      PermissionOperation = "update"
	PermissionDelete      PermissionOperation = "delete"
	PermissionPost        PermissionOperation = "post"
	PermissionUndoPosting PermissionOperation = "undo-posting"
)

// RoleDefinition contains additive grants, not system/Manager privileges.
// Omitted objects, fields and commands grant nothing. Object operations do not
// implicitly grant fields; command access does not grant underlying operations.
type RoleDefinition struct {
	Format   int                 `yaml:"format" json:"format"`
	ID       uuid.UUID           `yaml:"id" json:"id"`
	Name     string              `yaml:"name" json:"name"`
	Title    LocalizedText       `yaml:"title" json:"title"`
	Objects  []ObjectPermission  `yaml:"objects,omitempty" json:"objects,omitempty"`
	Commands []CommandPermission `yaml:"commands,omitempty" json:"commands,omitempty"`
}

type ObjectPermission struct {
	Object     uuid.UUID             `yaml:"object" json:"object"`
	Operations []PermissionOperation `yaml:"operations,omitempty" json:"operations,omitempty"`
	Fields     []FieldPermission     `yaml:"fields,omitempty" json:"fields,omitempty"`
}

// Field is a canonical UUID for an attribute/table part or a lowercase standard
// field key (e.g. ref, code, description). Names and translated titles are never
// security identifiers. A table part grant does not grant its columns.
type FieldPermission struct {
	Field      string                `yaml:"field" json:"field"`
	Operations []PermissionOperation `yaml:"operations" json:"operations"`
}

// Commands are scoped to the form UUID, since command IDs are unique per form.
// Standard autogenerated commands are controlled by their object operations;
// these grants address commands explicitly declared in managed form YAML.
type CommandPermission struct {
	Form    uuid.UUID `yaml:"form" json:"form"`
	Command uuid.UUID `yaml:"command" json:"command"`
}

func DecodeRole(source string, reader io.Reader, manifest project.Project) (RoleDefinition, error) {
	var value RoleDefinition
	if err := decodeStrict(source, reader, &value); err != nil {
		return RoleDefinition{}, err
	}
	if err := ValidateRole(source, value, manifest); err != nil {
		return RoleDefinition{}, err
	}
	return value, nil
}

// ValidateRole checks structure. Catalog validation additionally checks object
// and field ownership; publication validates every referenced form command.
func ValidateRole(source string, value RoleDefinition, manifest project.Project) error {
	issues := validateBase(value.Format, value.ID, value.Name, value.Title, manifest)
	if len(value.Objects)+len(value.Commands) > MaxRolePermissions {
		return fmt.Errorf("validate %s: role exceeds %d permissions", source, MaxRolePermissions)
	}
	count := len(value.Objects) + len(value.Commands)
	objects := make(map[uuid.UUID]bool, len(value.Objects))
	for index, object := range value.Objects {
		prefix := fmt.Sprintf("objects[%d]", index)
		if object.Object.IsZero() || objects[object.Object] {
			issues = append(issues, prefix+".object must be a unique non-zero UUID")
		}
		objects[object.Object] = true
		issues = append(issues, validatePermissionOperations(prefix+".operations", object.Operations, false)...)
		count += len(object.Fields)
		if count > MaxRolePermissions {
			return fmt.Errorf("validate %s: role exceeds %d permissions including fields", source, MaxRolePermissions)
		}
		fields := make(map[string]bool, len(object.Fields))
		for fieldIndex, field := range object.Fields {
			fieldPrefix := fmt.Sprintf("%s.fields[%d]", prefix, fieldIndex)
			if !validPermissionField(field.Field) {
				issues = append(issues, fieldPrefix+".field must be a canonical UUID or lowercase standard field key")
			}
			if fields[field.Field] {
				issues = append(issues, fieldPrefix+".field must be unique within the object")
			}
			fields[field.Field] = true
			issues = append(issues, validatePermissionOperations(fieldPrefix+".operations", field.Operations, true)...)
		}
	}
	commands := make(map[CommandPermission]bool, len(value.Commands))
	for index, command := range value.Commands {
		if command.Form.IsZero() || command.Command.IsZero() || commands[command] {
			issues = append(issues, fmt.Sprintf("commands[%d] must be a unique pair of non-zero form and command UUIDs", index))
		}
		commands[command] = true
	}
	return issuesError(source, value.Format, issues)
}

func validatePermissionOperations(path string, operations []PermissionOperation, field bool) []string {
	maximum := 6
	if field {
		maximum = 2
	}
	if len(operations) > maximum || field && len(operations) == 0 {
		return []string{fmt.Sprintf("%s has an invalid operation count (maximum %d)", path, maximum)}
	}
	var issues []string
	seen := make(map[PermissionOperation]bool, len(operations))
	for _, operation := range operations {
		valid := operation == PermissionRead || operation == PermissionUpdate
		if !field {
			valid = valid || operation == PermissionCreate || operation == PermissionDelete || operation == PermissionPost || operation == PermissionUndoPosting
		}
		if !valid || seen[operation] {
			issues = append(issues, path+" contains an unsupported or duplicate operation")
		}
		seen[operation] = true
	}
	return issues
}

func validPermissionField(field string) bool {
	if id, err := uuid.Parse(field); err == nil {
		return !id.IsZero() && id.String() == field
	}
	if len(field) == 0 || len(field) > 32 {
		return false
	}
	for _, character := range field {
		if character < 'a' || character > 'z' {
			return false
		}
	}
	return true
}

func (catalog *Catalog) Role(name string) (RoleDefinition, bool) {
	index, ok := catalog.roleByName[strings.ToLower(name)]
	if !ok {
		return RoleDefinition{}, false
	}
	return cloneRole(catalog.Roles[index]), true
}

func (catalog *Catalog) RoleByID(id uuid.UUID) (RoleDefinition, bool) {
	index, ok := catalog.roleByID[id]
	if !ok {
		return RoleDefinition{}, false
	}
	return cloneRole(catalog.Roles[index]), true
}

func cloneRole(value RoleDefinition) RoleDefinition {
	value.Title = cloneTitle(value.Title)
	value.Objects = slices.Clone(value.Objects)
	for index := range value.Objects {
		object := &value.Objects[index]
		object.Operations = slices.Clone(object.Operations)
		object.Fields = slices.Clone(object.Fields)
		for field := range object.Fields {
			object.Fields[field].Operations = slices.Clone(object.Fields[field].Operations)
		}
	}
	value.Commands = slices.Clone(value.Commands)
	return value
}
