package metadata

import (
	"fmt"
	"io"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/k33alexey/MetaLab/internal/project"
	"github.com/k33alexey/MetaLab/internal/uuid"
)

const RoleKind Kind = "roles"

// Limits apply to decoded JSON as well as bounded YAML sources.
const MaxRolePermissions = 10_000
const MaxRoleComment = 4_000

type PermissionOperation string

const (
	PermissionRead        PermissionOperation = "read"
	PermissionCreate      PermissionOperation = "create"
	PermissionUpdate      PermissionOperation = "update"
	PermissionDelete      PermissionOperation = "delete"
	PermissionPost        PermissionOperation = "post"
	PermissionUndoPosting PermissionOperation = "undo-posting"
	// PermissionView is the right to see an object in the interface, as
	// distinct from reading it in code. It is the most common right there is:
	// in the reference configuration it appears 1759 times against 1357 for
	// Read - a role that may compute with data is routinely not a role that
	// may open its list.
	PermissionView PermissionOperation = "view"
	// PermissionTotalsControl is the right to manage a register's
	// pre-aggregated totals - the stored balances, not the movements.
	PermissionTotalsControl PermissionOperation = "totals-control"
)

// objectOperations lists every operation an object permission may carry, in a
// stable order: it decides how rights are shown and in what order they are
// compiled, and a set would make both depend on map iteration.
var objectOperations = []PermissionOperation{
	PermissionRead, PermissionView, PermissionCreate, PermissionUpdate,
	PermissionDelete, PermissionPost, PermissionUndoPosting, PermissionTotalsControl,
}

// RoleDefinition contains additive grants, not system/Manager privileges.
// Omitted objects, fields and commands grant nothing. Object operations do not
// implicitly grant fields; command access does not grant underlying operations.
type RoleDefinition struct {
	Format   int                 `yaml:"format" json:"format"`
	ID       uuid.UUID           `yaml:"id" json:"id"`
	Name     string              `yaml:"name" json:"name"`
	Title    LocalizedText       `yaml:"title" json:"title"`
	Comment  string              `yaml:"comment,omitempty" json:"comment,omitempty"`
	Objects  []ObjectPermission  `yaml:"objects,omitempty" json:"objects,omitempty"`
	Commands []CommandPermission `yaml:"commands,omitempty" json:"commands,omitempty"`
	// GrantNewObjectsByDefault: a newly created metadata object automatically
	// gets PermissionRead in this role, instead of staying inaccessible until
	// a developer configures it by hand.
	GrantNewObjectsByDefault bool `yaml:"grant_new_objects_by_default,omitempty" json:"grantNewObjectsByDefault,omitempty"`
	// GrantNewFieldsByDefault: the same, but for a new attribute/table part
	// added to an object this role already has some access to - it never
	// grants a field on an object the role has no ObjectPermission entry
	// for at all.
	GrantNewFieldsByDefault bool `yaml:"grant_new_fields_by_default,omitempty" json:"grantNewFieldsByDefault,omitempty"`
	// PolicyTemplates are rules named once and reused by this role's own
	// restrictions. They grant nothing by themselves.
	PolicyTemplates []PolicyTemplate `yaml:"policy_templates,omitempty" json:"policyTemplates,omitempty"`
}

type ObjectPermission struct {
	Object     uuid.UUID             `yaml:"object" json:"object"`
	Operations []PermissionOperation `yaml:"operations,omitempty" json:"operations,omitempty"`
	Fields     []FieldPermission     `yaml:"fields,omitempty" json:"fields,omitempty"`
	// Policies narrow which rows the granted operations reach. They never widen
	// access: an object with no operation grant stays unreachable regardless.
	Policies []AccessPolicy `yaml:"policies,omitempty" json:"policies,omitempty"`
}

// Field is a canonical UUID for an attribute/table part or a lowercase standard
// field key (e.g. ref, code, description). Names and translated titles are never
// security identifiers. A table part grant does not grant its columns.
type FieldPermission struct {
	Field      string                `yaml:"field" json:"field"`
	Operations []PermissionOperation `yaml:"operations" json:"operations"`
}

// Commands are scoped to the form UUID, since command IDs are unique per form.
// Standard autogenerated commands are controlled by their object operations;
// these grants address commands explicitly declared in managed form YAML.
type CommandPermission struct {
	Form    uuid.UUID `yaml:"form" json:"form"`
	Command uuid.UUID `yaml:"command" json:"command"`
}

func DecodeRole(source string, reader io.Reader, manifest project.Project) (RoleDefinition, error) {
	var value RoleDefinition
	if err := decodeStrict(source, reader, &value); err != nil {
		return RoleDefinition{}, err
	}
	if err := ValidateRole(source, value, manifest); err != nil {
		return RoleDefinition{}, err
	}
	return value, nil
}

// ValidateRole checks structure. Catalog validation additionally checks object
// and field ownership; publication validates every referenced form command.
func ValidateRole(source string, value RoleDefinition, manifest project.Project) error {
	issues := validateBase(value.Format, value.ID, value.Name, value.Title, manifest)
	if !utf8.ValidString(value.Comment) || utf8.RuneCountInString(value.Comment) > MaxRoleComment {
		issues = append(issues, fmt.Sprintf("comment must be valid UTF-8 of at most %d characters", MaxRoleComment))
	}
	if len(value.Objects)+len(value.Commands) > MaxRolePermissions {
		return fmt.Errorf("validate %s: role exceeds %d permissions", source, MaxRolePermissions)
	}
	issues = append(issues, validatePolicyTemplates(value.PolicyTemplates)...)
	// Name to declared parameter count: a restriction must supply one field per
	// template parameter, so the arity travels with the name.
	templates := make(map[string]int, len(value.PolicyTemplates))
	for _, template := range value.PolicyTemplates {
		templates[template.Name] = len(template.Parameters)
	}
	count := len(value.Objects) + len(value.Commands)
	objects := make(map[uuid.UUID]bool, len(value.Objects))
	for index, object := range value.Objects {
		prefix := fmt.Sprintf("objects[%d]", index)
		if object.Object.IsZero() || objects[object.Object] {
			issues = append(issues, prefix+".object must be a unique non-zero UUID")
		}
		objects[object.Object] = true
		issues = append(issues, validatePermissionOperations(prefix+".operations", object.Operations, false)...)
		issues = append(issues, validatePolicies(prefix+".policies", object.Policies, templates)...)
		count += len(object.Fields) + len(object.Policies)
		if count > MaxRolePermissions {
			return fmt.Errorf("validate %s: role exceeds %d permissions including fields", source, MaxRolePermissions)
		}
		fields := make(map[string]bool, len(object.Fields))
		for fieldIndex, field := range object.Fields {
			fieldPrefix := fmt.Sprintf("%s.fields[%d]", prefix, fieldIndex)
			if !validPermissionField(field.Field) {
				issues = append(issues, fieldPrefix+".field must be a canonical UUID or lowercase standard field key")
			}
			if fields[field.Field] {
				issues = append(issues, fieldPrefix+".field must be unique within the object")
			}
			fields[field.Field] = true
			issues = append(issues, validatePermissionOperations(fieldPrefix+".operations", field.Operations, true)...)
		}
	}
	commands := make(map[CommandPermission]bool, len(value.Commands))
	for index, command := range value.Commands {
		if command.Form.IsZero() || command.Command.IsZero() || commands[command] {
			issues = append(issues, fmt.Sprintf("commands[%d] must be a unique pair of non-zero form and command UUIDs", index))
		}
		commands[command] = true
	}
	return issuesError(source, value.Format, issues)
}

func validatePermissionOperations(path string, operations []PermissionOperation, field bool) []string {
	// Fields carry only read and update: a field is data, and everything else
	// on the list is about the object as a whole.
	maximum := len(objectOperations)
	if field {
		maximum = 2
	}
	if len(operations) > maximum || field && len(operations) == 0 {
		return []string{fmt.Sprintf("%s has an invalid operation count (maximum %d)", path, maximum)}
	}
	var issues []string
	seen := make(map[PermissionOperation]bool, len(operations))
	for _, operation := range operations {
		valid := operation == PermissionRead || operation == PermissionUpdate
		if !field {
			valid = slices.Contains(objectOperations, operation)
		}
		if !valid || seen[operation] {
			issues = append(issues, path+" contains an unsupported or duplicate operation")
		}
		seen[operation] = true
	}
	return issues
}

func validPermissionField(field string) bool {
	if id, err := uuid.Parse(field); err == nil {
		return !id.IsZero() && id.String() == field
	}
	if len(field) == 0 || len(field) > 32 {
		return false
	}
	for _, character := range field {
		if character < 'a' || character > 'z' {
			return false
		}
	}
	return true
}

func (catalog *Catalog) Role(name string) (RoleDefinition, bool) {
	index, ok := catalog.roleByName[strings.ToLower(name)]
	if !ok {
		return RoleDefinition{}, false
	}
	return cloneRole(catalog.Roles[index]), true
}

func (catalog *Catalog) RoleByID(id uuid.UUID) (RoleDefinition, bool) {
	index, ok := catalog.roleByID[id]
	if !ok {
		return RoleDefinition{}, false
	}
	return cloneRole(catalog.Roles[index]), true
}

func cloneRole(value RoleDefinition) RoleDefinition {
	value.Title = cloneTitle(value.Title)
	value.Objects = slices.Clone(value.Objects)
	for index := range value.Objects {
		object := &value.Objects[index]
		object.Operations = slices.Clone(object.Operations)
		object.Fields = slices.Clone(object.Fields)
		for field := range object.Fields {
			object.Fields[field].Operations = slices.Clone(object.Fields[field].Operations)
		}
		object.Policies = clonePolicies(object.Policies)
	}
	value.Commands = slices.Clone(value.Commands)
	value.PolicyTemplates = clonePolicyTemplates(value.PolicyTemplates)
	return value
}

// GrantObjectReadByDefault adds PermissionRead for objectID if the role does
// not already grant any operation on it - used when GrantNewObjectsByDefault
// is set, right after a new metadata object is created. Reports whether it
// changed the role.
func (role *RoleDefinition) GrantObjectReadByDefault(objectID uuid.UUID) bool {
	for index := range role.Objects {
		if role.Objects[index].Object == objectID {
			if slices.Contains(role.Objects[index].Operations, PermissionRead) {
				return false
			}
			role.Objects[index].Operations = append(role.Objects[index].Operations, PermissionRead)
			return true
		}
	}
	role.Objects = append(role.Objects, ObjectPermission{Object: objectID, Operations: []PermissionOperation{PermissionRead}})
	return true
}

// GrantFieldReadByDefault adds PermissionRead for fieldKey on objectID, but
// only when the role already has an ObjectPermission entry for objectID -
// used when GrantNewFieldsByDefault is set, right after a new attribute or
// table part is added to an object. A role with no access to the object at
// all does not get access to one of its fields in isolation. Reports whether
// it changed the role.
func (role *RoleDefinition) GrantFieldReadByDefault(objectID uuid.UUID, fieldKey string) bool {
	for index := range role.Objects {
		if role.Objects[index].Object != objectID {
			continue
		}
		for fieldIndex := range role.Objects[index].Fields {
			if role.Objects[index].Fields[fieldIndex].Field == fieldKey {
				if slices.Contains(role.Objects[index].Fields[fieldIndex].Operations, PermissionRead) {
					return false
				}
				role.Objects[index].Fields[fieldIndex].Operations = append(role.Objects[index].Fields[fieldIndex].Operations, PermissionRead)
				return true
			}
		}
		role.Objects[index].Fields = append(role.Objects[index].Fields, FieldPermission{Field: fieldKey, Operations: []PermissionOperation{PermissionRead}})
		return true
	}
	return false
}

// ObjectOperations lists every right an object permission can carry, in the
// order they are shown and compiled.
func ObjectOperations() []PermissionOperation { return slices.Clone(objectOperations) }
