// Package compiler translates the BSL syntax tree into MetaLab bytecode.
package compiler

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	"github.com/k33alexey/MetaLab/internal/bsl/bytecode"
	"github.com/k33alexey/MetaLab/internal/bsl/syntax"
)

// CompileSource performs the complete prototype frontend and compilation pass.
func CompileSource(filename, source string) (*bytecode.Program, []syntax.Diagnostic) {
	module, diagnostics := syntax.Parse(filename, source)
	if len(diagnostics) != 0 {
		return nil, diagnostics
	}
	return Compile(filename, module)
}

// Compile translates a parsed module into validated bytecode.
func Compile(filename string, module *syntax.Module) (*bytecode.Program, []syntax.Diagnostic) {
	program := &bytecode.Program{Version: bytecode.Version}
	state := compiler{filename: filename}
	names := make(map[string]bool, len(module.Routines))
	for _, routine := range module.Routines {
		folded := strings.ToLower(routine.Name)
		if names[folded] {
			state.report(routine.SourceSpan, "BSL3001", "duplicate routine "+routine.Name)
			continue
		}
		names[folded] = true
		compiled := state.compileRoutine(routine)
		if compiled != nil {
			program.Functions = append(program.Functions, *compiled)
		}
	}
	if len(state.diagnostics) != 0 {
		return nil, state.diagnostics
	}
	if err := program.Validate(); err != nil {
		state.report(syntax.Span{}, "BSL3002", "invalid generated bytecode: "+err.Error())
		return nil, state.diagnostics
	}
	return program, nil
}

type compiler struct {
	filename    string
	diagnostics []syntax.Diagnostic
}

type functionCompiler struct {
	owner      *compiler
	routine    *syntax.Routine
	function   bytecode.Function
	parameters map[string]uint16
	depth      int
	maximum    int
}

func (c *compiler) compileRoutine(routine *syntax.Routine) *bytecode.Function {
	if len(routine.Parameters) > math.MaxUint16 {
		c.report(routine.SourceSpan, "BSL3003", "too many routine parameters")
		return nil
	}
	state := functionCompiler{
		owner: c, routine: routine,
		function: bytecode.Function{
			Name: routine.Name, IsFunction: routine.Function, Export: routine.Export,
			Arity: uint16(len(routine.Parameters)),
		},
		parameters: make(map[string]uint16, len(routine.Parameters)),
	}
	for index, parameter := range routine.Parameters {
		name := strings.ToLower(parameter.Name)
		if _, exists := state.parameters[name]; exists {
			c.report(parameter.Span, "BSL3004", "duplicate parameter "+parameter.Name)
			continue
		}
		state.parameters[name] = uint16(index)
	}

	for _, statement := range routine.Body {
		state.compileStatement(statement)
	}
	if len(state.function.Code) == 0 || state.function.Code[len(state.function.Code)-1].Opcode != bytecode.OpReturn {
		state.emitConstant(bytecode.Undefined(), routine.SourceSpan)
		state.emit(bytecode.OpReturn, 0, routine.SourceSpan)
	}
	state.function.MaxStack = uint16(state.maximum)
	return &state.function
}

func (c *functionCompiler) compileStatement(statement syntax.Statement) {
	switch node := statement.(type) {
	case *syntax.ReturnStatement:
		if node.Value == nil {
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
		} else {
			c.compileExpression(node.Value)
		}
		c.emit(bytecode.OpReturn, 0, node.SourceSpan)
	default:
		c.owner.report(statement.NodeSpan(), "BSL3005", fmt.Sprintf("unsupported statement %T", statement))
	}
}

func (c *functionCompiler) compileExpression(expression syntax.Expression) {
	switch node := expression.(type) {
	case *syntax.NumberExpression:
		value, err := strconv.ParseFloat(node.Text, 64)
		if err != nil {
			c.owner.report(node.SourceSpan, "BSL3006", "invalid number "+node.Text)
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
			return
		}
		c.emitConstant(bytecode.Number(value), node.SourceSpan)
	case *syntax.StringExpression:
		c.emitConstant(bytecode.String(node.Value), node.SourceSpan)
	case *syntax.IdentifierExpression:
		index, ok := c.parameters[strings.ToLower(node.Name)]
		if !ok {
			c.owner.report(node.SourceSpan, "BSL3007", "unknown identifier "+node.Name)
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
			return
		}
		c.emit(bytecode.OpLoadLocal, index, node.SourceSpan)
	case *syntax.GroupExpression:
		c.compileExpression(node.Expression)
	case *syntax.UnaryExpression:
		c.compileExpression(node.Operand)
		if node.Operator == syntax.Minus {
			c.emit(bytecode.OpNegate, 0, node.SourceSpan)
		}
	case *syntax.BinaryExpression:
		c.compileExpression(node.Left)
		c.compileExpression(node.Right)
		opcode := bytecode.OpAdd
		switch node.Operator {
		case syntax.Plus:
			opcode = bytecode.OpAdd
		case syntax.Minus:
			opcode = bytecode.OpSubtract
		case syntax.Star:
			opcode = bytecode.OpMultiply
		case syntax.Slash:
			opcode = bytecode.OpDivide
		default:
			c.owner.report(node.SourceSpan, "BSL3008", "unsupported binary operator "+node.Operator.String())
		}
		c.emit(opcode, 0, node.SourceSpan)
	default:
		c.owner.report(expression.NodeSpan(), "BSL3009", fmt.Sprintf("unsupported expression %T", expression))
		c.emitConstant(bytecode.Undefined(), expression.NodeSpan())
	}
}

func (c *functionCompiler) emitConstant(value bytecode.Value, span syntax.Span) {
	if len(c.function.Constants) >= math.MaxUint16 {
		c.owner.report(span, "BSL3010", "too many constants in routine")
		return
	}
	index := uint16(len(c.function.Constants))
	c.function.Constants = append(c.function.Constants, value)
	c.emit(bytecode.OpConstant, index, span)
}

func (c *functionCompiler) emit(opcode bytecode.Opcode, operand uint16, span syntax.Span) {
	c.function.Code = append(c.function.Code, bytecode.Instruction{Opcode: opcode, Operand: operand, Span: span})
	switch opcode {
	case bytecode.OpConstant, bytecode.OpLoadLocal:
		c.depth++
	case bytecode.OpAdd, bytecode.OpSubtract, bytecode.OpMultiply, bytecode.OpDivide:
		c.depth--
	case bytecode.OpReturn:
		c.depth--
	}
	if c.depth > c.maximum {
		c.maximum = c.depth
	}
}

func (c *compiler) report(span syntax.Span, code, message string) {
	if span.Start.Line == 0 {
		span.Start.Line, span.Start.Column = 1, 1
	}
	c.diagnostics = append(c.diagnostics, syntax.Diagnostic{
		Filename: c.filename, Code: code, Message: message, Span: span,
	})
}
