// Package compiler translates the BSL syntax tree into MetaLab bytecode.
package compiler

import (
	"fmt"
	"math"
	"strings"

	"github.com/k33alexey/MetaLab/internal/bsl/bytecode"
	"github.com/k33alexey/MetaLab/internal/bsl/syntax"
)

// CompileSource performs the complete frontend and compilation pass.
func CompileSource(filename, source string) (*bytecode.Program, []syntax.Diagnostic) {
	module, diagnostics := syntax.Parse(filename, source)
	if len(diagnostics) != 0 {
		return nil, diagnostics
	}
	return Compile(filename, module)
}

// Compile translates a parsed module into validated bytecode.
func Compile(filename string, module *syntax.Module) (*bytecode.Program, []syntax.Diagnostic) {
	program := &bytecode.Program{Version: bytecode.Version}
	state := compiler{filename: filename}
	names := make(map[string]bool, len(module.Routines))
	for _, routine := range module.Routines {
		folded := strings.ToLower(routine.Name)
		if names[folded] {
			state.report(routine.SourceSpan, "BSL3001", "duplicate routine "+routine.Name)
			continue
		}
		names[folded] = true
		compiled := state.compileRoutine(routine)
		if compiled != nil {
			program.Functions = append(program.Functions, *compiled)
		}
	}
	if len(state.diagnostics) != 0 {
		return nil, state.diagnostics
	}
	if err := program.Validate(); err != nil {
		state.report(syntax.Span{}, "BSL3002", "invalid generated bytecode: "+err.Error())
		return nil, state.diagnostics
	}
	return program, nil
}

type compiler struct {
	filename    string
	diagnostics []syntax.Diagnostic
}

type functionCompiler struct {
	owner     *compiler
	routine   *syntax.Routine
	function  bytecode.Function
	locals    map[string]uint16
	nextLocal int
	loops     []loopContext
	depth     int
	maximum   int
}

type loopContext struct {
	continueTarget int
	breakJumps     []int
	continueJumps  []int
}

func (c *compiler) compileRoutine(routine *syntax.Routine) *bytecode.Function {
	if len(routine.Parameters) > math.MaxUint16 {
		c.report(routine.SourceSpan, "BSL3003", "too many routine parameters")
		return nil
	}
	state := functionCompiler{
		owner: c, routine: routine,
		function: bytecode.Function{
			Name: routine.Name, IsFunction: routine.Function, Export: routine.Export,
			Arity: uint16(len(routine.Parameters)),
		},
		locals: make(map[string]uint16, len(routine.Parameters)), nextLocal: len(routine.Parameters),
	}
	for index, parameter := range routine.Parameters {
		name := strings.ToLower(parameter.Name)
		if _, exists := state.locals[name]; exists {
			c.report(parameter.Span, "BSL3004", "duplicate parameter "+parameter.Name)
			continue
		}
		state.locals[name] = uint16(index)
	}

	for _, statement := range routine.Body {
		state.compileStatement(statement)
	}
	if len(state.function.Code) == 0 || state.function.Code[len(state.function.Code)-1].Opcode != bytecode.OpReturn || state.hasJumpTarget(len(state.function.Code)) {
		state.emitConstant(bytecode.Undefined(), routine.SourceSpan)
		state.emit(bytecode.OpReturn, 0, routine.SourceSpan)
	}
	if state.nextLocal > math.MaxUint16 {
		c.report(routine.SourceSpan, "BSL3011", "too many local variables in routine")
	}
	state.function.LocalCount = uint16(state.nextLocal)
	state.function.MaxStack = uint16(state.maximum)
	return &state.function
}

func (c *functionCompiler) compileStatement(statement syntax.Statement) {
	switch node := statement.(type) {
	case *syntax.ReturnStatement:
		if node.Value == nil {
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
		} else {
			c.compileExpression(node.Value)
		}
		c.emit(bytecode.OpReturn, 0, node.SourceSpan)
	case *syntax.AssignmentStatement:
		c.compileExpression(node.Value)
		c.emit(bytecode.OpStoreLocal, c.ensureLocal(node.Name, node.SourceSpan), node.SourceSpan)
	case *syntax.IfStatement:
		c.compileIf(node)
	case *syntax.WhileStatement:
		c.compileWhile(node)
	case *syntax.ForStatement:
		c.compileFor(node)
	case *syntax.ForEachStatement:
		c.compileForEach(node)
	case *syntax.BreakStatement:
		c.compileLoopControl(node.SourceSpan, true)
	case *syntax.ContinueStatement:
		c.compileLoopControl(node.SourceSpan, false)
	default:
		c.owner.report(statement.NodeSpan(), "BSL3005", fmt.Sprintf("unsupported statement %T", statement))
	}
}

func (c *functionCompiler) compileExpression(expression syntax.Expression) {
	switch node := expression.(type) {
	case *syntax.NumberExpression:
		value, err := bytecode.ParseNumber(node.Text)
		if err != nil {
			c.owner.report(node.SourceSpan, "BSL3006", "invalid number "+node.Text)
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
			return
		}
		c.emitConstant(value, node.SourceSpan)
	case *syntax.StringExpression:
		c.emitConstant(bytecode.String(node.Value), node.SourceSpan)
	case *syntax.BooleanExpression:
		c.emitConstant(bytecode.Boolean(node.Value), node.SourceSpan)
	case *syntax.DateExpression:
		value, err := bytecode.ParseDate(node.Text)
		if err != nil {
			c.owner.report(node.SourceSpan, "BSL3014", "invalid date literal: "+err.Error())
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
			return
		}
		c.emitConstant(value, node.SourceSpan)
	case *syntax.UndefinedExpression:
		c.emitConstant(bytecode.Undefined(), node.SourceSpan)
	case *syntax.NullExpression:
		c.emitConstant(bytecode.Null(), node.SourceSpan)
	case *syntax.IdentifierExpression:
		index, ok := c.locals[strings.ToLower(node.Name)]
		if !ok {
			c.owner.report(node.SourceSpan, "BSL3007", "unknown identifier "+node.Name)
			c.emitConstant(bytecode.Undefined(), node.SourceSpan)
			return
		}
		c.emit(bytecode.OpLoadLocal, index, node.SourceSpan)
	case *syntax.GroupExpression:
		c.compileExpression(node.Expression)
	case *syntax.UnaryExpression:
		c.compileExpression(node.Operand)
		switch node.Operator {
		case syntax.Plus:
			c.emit(bytecode.OpPositive, 0, node.SourceSpan)
		case syntax.Minus:
			c.emit(bytecode.OpNegate, 0, node.SourceSpan)
		case syntax.Not:
			c.emit(bytecode.OpNot, 0, node.SourceSpan)
		}
	case *syntax.BinaryExpression:
		if node.Operator == syntax.And || node.Operator == syntax.Or {
			c.compileLogical(node)
			return
		}
		c.compileExpression(node.Left)
		c.compileExpression(node.Right)
		opcode := bytecode.OpAdd
		switch node.Operator {
		case syntax.Plus:
			opcode = bytecode.OpAdd
		case syntax.Minus:
			opcode = bytecode.OpSubtract
		case syntax.Star:
			opcode = bytecode.OpMultiply
		case syntax.Slash:
			opcode = bytecode.OpDivide
		case syntax.Percent:
			opcode = bytecode.OpModulo
		case syntax.Equal:
			opcode = bytecode.OpEqual
		case syntax.NotEqual:
			opcode = bytecode.OpNotEqual
		case syntax.Less:
			opcode = bytecode.OpLess
		case syntax.LessEqual:
			opcode = bytecode.OpLessEqual
		case syntax.Greater:
			opcode = bytecode.OpGreater
		case syntax.GreaterEqual:
			opcode = bytecode.OpGreaterEqual
		case syntax.And:
			opcode = bytecode.OpAnd
		case syntax.Or:
			opcode = bytecode.OpOr
		default:
			c.owner.report(node.SourceSpan, "BSL3008", "unsupported binary operator "+node.Operator.String())
		}
		c.emit(opcode, 0, node.SourceSpan)
	default:
		c.owner.report(expression.NodeSpan(), "BSL3009", fmt.Sprintf("unsupported expression %T", expression))
		c.emitConstant(bytecode.Undefined(), expression.NodeSpan())
	}
}

func (c *functionCompiler) compileLogical(expression *syntax.BinaryExpression) {
	c.compileExpression(expression.Left)
	opcode := bytecode.OpJumpIfFalseKeep
	if expression.Operator == syntax.Or {
		opcode = bytecode.OpJumpIfTrueKeep
	}
	endJump := c.emitJump(opcode, expression.SourceSpan)
	c.emit(bytecode.OpPop, 0, expression.SourceSpan)
	c.compileExpression(expression.Right)
	c.emit(bytecode.OpBoolean, 0, expression.Right.NodeSpan())
	c.patchJump(endJump, len(c.function.Code), expression.SourceSpan)
}

func (c *functionCompiler) compileIf(statement *syntax.IfStatement) {
	endJumps := make([]int, 0, len(statement.Branches))
	for _, branch := range statement.Branches {
		c.compileExpression(branch.Condition)
		falseJump := c.emitJump(bytecode.OpJumpIfFalse, branch.SourceSpan)
		for _, child := range branch.Body {
			c.compileStatement(child)
		}
		endJumps = append(endJumps, c.emitJump(bytecode.OpJump, branch.SourceSpan))
		c.patchJump(falseJump, len(c.function.Code), branch.SourceSpan)
	}
	for _, child := range statement.ElseBody {
		c.compileStatement(child)
	}
	end := len(c.function.Code)
	for _, jump := range endJumps {
		c.patchJump(jump, end, statement.SourceSpan)
	}
}

func (c *functionCompiler) compileWhile(statement *syntax.WhileStatement) {
	start := len(c.function.Code)
	c.compileExpression(statement.Condition)
	exitJump := c.emitJump(bytecode.OpJumpIfFalse, statement.SourceSpan)
	c.loops = append(c.loops, loopContext{continueTarget: start})
	for _, child := range statement.Body {
		c.compileStatement(child)
	}
	loop := c.loops[len(c.loops)-1]
	c.loops = c.loops[:len(c.loops)-1]
	c.emitTargetJump(bytecode.OpJump, start, statement.SourceSpan)
	exit := len(c.function.Code)
	c.patchJump(exitJump, exit, statement.SourceSpan)
	for _, jump := range loop.breakJumps {
		c.patchJump(jump, exit, statement.SourceSpan)
	}
}

func (c *functionCompiler) compileFor(statement *syntax.ForStatement) {
	counter := c.ensureLocal(statement.Variable, statement.SourceSpan)
	limit := c.allocateLocal(statement.SourceSpan)
	c.compileExpression(statement.Initial)
	c.emit(bytecode.OpStoreLocal, counter, statement.SourceSpan)
	c.compileExpression(statement.Limit)
	c.emit(bytecode.OpStoreLocal, limit, statement.SourceSpan)

	start := len(c.function.Code)
	c.emit(bytecode.OpLoadLocal, counter, statement.SourceSpan)
	c.emit(bytecode.OpLoadLocal, limit, statement.SourceSpan)
	c.emit(bytecode.OpLessEqual, 0, statement.SourceSpan)
	exitJump := c.emitJump(bytecode.OpJumpIfFalse, statement.SourceSpan)
	c.loops = append(c.loops, loopContext{continueTarget: -1})
	for _, child := range statement.Body {
		c.compileStatement(child)
	}
	loopIndex := len(c.loops) - 1
	increment := len(c.function.Code)
	c.loops[loopIndex].continueTarget = increment
	for _, jump := range c.loops[loopIndex].continueJumps {
		c.patchJump(jump, increment, statement.SourceSpan)
	}
	loop := c.loops[loopIndex]
	c.loops = c.loops[:loopIndex]

	c.emit(bytecode.OpLoadLocal, counter, statement.SourceSpan)
	c.emitConstant(bytecode.Number(1), statement.SourceSpan)
	c.emit(bytecode.OpAdd, 0, statement.SourceSpan)
	c.emit(bytecode.OpStoreLocal, counter, statement.SourceSpan)
	c.emitTargetJump(bytecode.OpJump, start, statement.SourceSpan)
	exit := len(c.function.Code)
	c.patchJump(exitJump, exit, statement.SourceSpan)
	for _, jump := range loop.breakJumps {
		c.patchJump(jump, exit, statement.SourceSpan)
	}
}

func (c *functionCompiler) compileForEach(statement *syntax.ForEachStatement) {
	iterator := c.ensureLocal(statement.Variable, statement.SourceSpan)
	collection := c.allocateLocal(statement.SourceSpan)
	index := c.allocateLocal(statement.SourceSpan)
	c.compileExpression(statement.Collection)
	c.emit(bytecode.OpStoreLocal, collection, statement.SourceSpan)
	c.emitConstant(bytecode.Number(0), statement.SourceSpan)
	c.emit(bytecode.OpStoreLocal, index, statement.SourceSpan)

	start := len(c.function.Code)
	c.emit(bytecode.OpLoadLocal, index, statement.SourceSpan)
	c.emit(bytecode.OpLoadLocal, collection, statement.SourceSpan)
	c.emit(bytecode.OpArrayLength, 0, statement.SourceSpan)
	c.emit(bytecode.OpLess, 0, statement.SourceSpan)
	exitJump := c.emitJump(bytecode.OpJumpIfFalse, statement.SourceSpan)
	c.emit(bytecode.OpLoadLocal, collection, statement.SourceSpan)
	c.emit(bytecode.OpLoadLocal, index, statement.SourceSpan)
	c.emit(bytecode.OpArrayElement, 0, statement.SourceSpan)
	c.emit(bytecode.OpStoreLocal, iterator, statement.SourceSpan)

	c.loops = append(c.loops, loopContext{continueTarget: -1})
	for _, child := range statement.Body {
		c.compileStatement(child)
	}
	loopIndex := len(c.loops) - 1
	increment := len(c.function.Code)
	c.loops[loopIndex].continueTarget = increment
	for _, jump := range c.loops[loopIndex].continueJumps {
		c.patchJump(jump, increment, statement.SourceSpan)
	}
	loop := c.loops[loopIndex]
	c.loops = c.loops[:loopIndex]

	c.emit(bytecode.OpLoadLocal, index, statement.SourceSpan)
	c.emitConstant(bytecode.Number(1), statement.SourceSpan)
	c.emit(bytecode.OpAdd, 0, statement.SourceSpan)
	c.emit(bytecode.OpStoreLocal, index, statement.SourceSpan)
	c.emitTargetJump(bytecode.OpJump, start, statement.SourceSpan)
	exit := len(c.function.Code)
	c.patchJump(exitJump, exit, statement.SourceSpan)
	for _, jump := range loop.breakJumps {
		c.patchJump(jump, exit, statement.SourceSpan)
	}
}

func (c *functionCompiler) compileLoopControl(span syntax.Span, breaking bool) {
	if len(c.loops) == 0 {
		name := "Continue"
		if breaking {
			name = "Break"
		}
		c.owner.report(span, "BSL3012", name+" is only allowed inside a loop")
		return
	}
	loop := &c.loops[len(c.loops)-1]
	if breaking {
		loop.breakJumps = append(loop.breakJumps, c.emitJump(bytecode.OpJump, span))
		return
	}
	if loop.continueTarget >= 0 {
		c.emitTargetJump(bytecode.OpJump, loop.continueTarget, span)
	} else {
		loop.continueJumps = append(loop.continueJumps, c.emitJump(bytecode.OpJump, span))
	}
}

func (c *functionCompiler) ensureLocal(name string, span syntax.Span) uint16 {
	folded := strings.ToLower(name)
	if index, ok := c.locals[folded]; ok {
		return index
	}
	index := c.allocateLocal(span)
	c.locals[folded] = index
	return index
}

func (c *functionCompiler) allocateLocal(span syntax.Span) uint16 {
	if c.nextLocal >= math.MaxUint16 {
		c.owner.report(span, "BSL3011", "too many local variables in routine")
		return 0
	}
	index := uint16(c.nextLocal)
	c.nextLocal++
	return index
}

func (c *functionCompiler) emitJump(opcode bytecode.Opcode, span syntax.Span) int {
	index := len(c.function.Code)
	c.emit(opcode, 0, span)
	return index
}

func (c *functionCompiler) emitTargetJump(opcode bytecode.Opcode, target int, span syntax.Span) {
	index := c.emitJump(opcode, span)
	c.patchJump(index, target, span)
}

func (c *functionCompiler) patchJump(index, target int, span syntax.Span) {
	if index < 0 || index >= len(c.function.Code) || target < 0 || target > math.MaxUint16 {
		c.owner.report(span, "BSL3013", "routine is too large for a control-flow jump")
		return
	}
	c.function.Code[index].Operand = uint16(target)
}

func (c *functionCompiler) hasJumpTarget(target int) bool {
	for _, instruction := range c.function.Code {
		if (instruction.Opcode == bytecode.OpJump || instruction.Opcode == bytecode.OpJumpIfFalse ||
			instruction.Opcode == bytecode.OpJumpIfTrueKeep || instruction.Opcode == bytecode.OpJumpIfFalseKeep) && int(instruction.Operand) == target {
			return true
		}
	}
	return false
}

func (c *functionCompiler) emitConstant(value bytecode.Value, span syntax.Span) {
	if len(c.function.Constants) >= math.MaxUint16 {
		c.owner.report(span, "BSL3010", "too many constants in routine")
		return
	}
	index := uint16(len(c.function.Constants))
	c.function.Constants = append(c.function.Constants, value)
	c.emit(bytecode.OpConstant, index, span)
}

func (c *functionCompiler) emit(opcode bytecode.Opcode, operand uint16, span syntax.Span) {
	c.function.Code = append(c.function.Code, bytecode.Instruction{Opcode: opcode, Operand: operand, Span: span})
	switch opcode {
	case bytecode.OpConstant, bytecode.OpLoadLocal:
		c.depth++
	case bytecode.OpStoreLocal, bytecode.OpJumpIfFalse, bytecode.OpPop:
		c.depth--
	case bytecode.OpAdd, bytecode.OpSubtract, bytecode.OpMultiply, bytecode.OpDivide,
		bytecode.OpModulo, bytecode.OpEqual, bytecode.OpNotEqual, bytecode.OpLess,
		bytecode.OpLessEqual, bytecode.OpGreater, bytecode.OpGreaterEqual,
		bytecode.OpAnd, bytecode.OpOr, bytecode.OpArrayElement:
		c.depth--
	case bytecode.OpReturn:
		c.depth--
	}
	if c.depth > c.maximum {
		c.maximum = c.depth
	}
}

func (c *compiler) report(span syntax.Span, code, message string) {
	if span.Start.Line == 0 {
		span.Start.Line, span.Start.Column = 1, 1
	}
	c.diagnostics = append(c.diagnostics, syntax.Diagnostic{
		Filename: c.filename, Code: code, Message: message, Span: span,
	})
}
